services:
  db:
    image: postgres:17
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spl
    ports:
      - "5432:5432"
    volumes:
      - spl_db_data_local:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

  web:
    build: .
    container_name: spl-next
    env_file: .env
    volumes:
      - ./cron.log:/var/log/cron.log
    ports:
      - "3000:3000"
volumes:
  spl_db_data_local:
