export type SplInventory = {
    uid:string,
    item_detail_id:number,
    player:string,
    created_date:string,
    created_tx:string,
    created_block_num:number,
    in_use:boolean,
    lock_days:number | null,
    unlock_date:string | null,
    unlock_tx:string | null,
    listed:boolean,
    stake_start_date:string | null,
    stake_end_date:string | null,
    boost:string | null,
    stake_plot:string | null,
    stake_region:string | null,
    id:number,
    name:string,
    type:string,
    sub_type:string | null,
    data:JSON | null,
    transferable:boolean,
    consumable:boolean,
    print_limit:number | null,
    total_printed:number,
    image_filename:string,
    rarity:string | null,
    quantity:number
  };
