import { Resource } from "@/constants/resource/resource";
import { ProductionPoints } from "./productionPoints";

export type RegionSummary = {
  worksites: Record<string, number>;
  players: Record<string, number>;
  rarities: Record<string, number>;
  deedTypes: Record<string, number>;
  plotStatuses: Record<string, number>;
  runiBoosts: Record<string, number>;
  totemBoosts: Record<string, number>;
  titleBoosts: Record<string, number>;
  deedRarityBoosts: Record<string, number>;
  runiCount: number;
  totalDecNeeded: number;
  totalDecInUse: number;
  totalDecStaked: number;
  deedsCount: number;
  rewardsPerHour: Record<Resource, number>;
  productionPoints: Record<Resource, ProductionPoints>;
  totalBasePP: number;
  totalBoostedPP: number;
  countEnergized: number;
  countLaborsLuck: number;
  countAbilityBoost: number;
  countBloodlinesBoost: number;
  countFoodDiscount: number;
  countDecStakeDiscount: number;
  totalAbilityBoostPP: number;
  totalBloodlinesBoostPP: number;
};
